try:
    a=10
    print(a)
    print(a/0)
except:
    print('hello')
finally:
    print("the try except block is finished")
